import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata = {
  title: "Robe Data Base",
  description: "Generated by Alamin",
  // 💡 সমাধান ১: এই অংশটি যোগ করুন
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1, // ঐচ্ছিক, তবে ছোট স্ক্রিনে জুম ব্লক করতে পারে
  },
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
